services:
  app:
    build: .
    ports:
      - "3000:3000"
    tmpfs:
      - /tmp/app:size=2G
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
